---
title: "child expenditure"
format: html
editor: visual
---

## Set Up

Setting up the library and getting the data.

```{r}
#### Workspace setup ####
library(tidyverse)
library(dplyr)
library(haven)
library(stata2r)

#### Download data ####

child_enforce_data <- read_dta("data/raw_data/annual_policy/policyvars01_19.dta")
head(child_enforce_data)
```

```{r}

# medicaid benefits
ggplot(child_enforce_data, aes(x = year, y = aca_mcaid_exp)) +
  geom_col(fill = "#1f77b4" ) + labs(x = "Year", y = "Number of people who have ACA Medicaid Expenditure", title = "People who have ACA Medicaid Expenditure Over Time (Years)") + theme_minimal() +  theme(plot.title = element_text(hjust = 0.5))  
```

```{r}
# max well fair benefits
ggplot(child_enforce_data, aes(x=year, y=logben3)) +
    geom_point()  + labs(x = "Year", y = "Max Welfare Benefits", title = "Max Welfare Benefits Over Time (Years)") + theme_minimal() +  theme(plot.title = element_text(hjust = 0.5))  

```

```{r}
# Parental
ggplot(child_enforce_data, aes(x = factor(year), fill = factor(parental))) +
  geom_bar(position = "stack") +
  labs(x = "Year", y = "Parental Consent for Abortion", fill = "Interest", title = "Distribution of Interest in Abortion by Parent Over Time (Years)") + theme_minimal() + theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 45, vjust = 0.5))  
```
